# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47456cb6a9654bd42b3217abe00ba10aa86d2386656e575fe2870b88a7d653e9b8a02313f95c509fcf89e742364d8ce8abe1d925db2c48d4c0da796c490ed0c7

test:
  secret_key_base: 8676b8c547ad253fa57df446d62e0b3572326fb4983ce68fd04a5a5ef8358321f2de0b27beb78cc233a179482e5b701eee5d09fe9ea6c8cef90d1ae3c57c3c60

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
